ci: release

diff --git a/.github/workflows/release-please.yaml b/.github/workflows/release-please.yaml
--- a/.github/workflows/release-please.yaml
+++ b/.github/workflows/release-please.yaml
@@ -1,32 +1,20 @@
 name: Release
 
+# release on push version tag, e.g. v0.3.2
 on:
   push:
-    branches:
-      - main
+    tags:
+      - 'v*.*.*'
 
 permissions:
   contents: write
-  pull-requests: write
 
 env:
   PYTHON_VERSION: 3.11
 
 jobs:
-  release-please:
-    runs-on: ubuntu-latest
-    outputs:
-      release_created: ${{ steps.release.outputs.release_created }}
-    steps:
-      - uses: GoogleCloudPlatform/release-please-action@v4
-        id: release
-        with:
-          release-type: python
-
   publish:
     runs-on: ubuntu-latest
-    needs: release-please
-    if: ${{ needs.release-please.outputs.release_created }}
     steps:
       - uses: actions/checkout@v3
 
@@ -45,11 +33,24 @@ jobs:
           python-version: ${{ env.PYTHON_VERSION }}
           cache: poetry
 
+      - name: Check if tag matches the package version
+        run: |
+          PKG_VERSION = $(poetry version -s)
+          TAG = ${GITHUB_REF#refs/tags/}
+          if [[ "v${PKG_VERSION}" != $TAG ]]; then
+            echo "Error: Tag ($TAG) does not match the package version (v${PKG_VERSION})."
+            exit 1
+
       - name: Install Dependencies using Poetry
-        run: poetry install
+        run: poetry build
+
+      - uses: ncipollo/release-action@v1
+        with:
+          generateReleaseNotes: true
+          artifacts: "dist/*"
 
       - name: Publish to PyPi
         env:
           PYPI_USERNAME: __token__
           PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}
-        run: poetry publish --build --username $PYPI_USERNAME --password $PYPI_PASSWORD
+        run: poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD
